version: '3.8'

services:
  pdf-converter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./temp:/temp
    environment:
      - MAX_WORKERS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 